version: "3.6"
services:
    phpfpmci:
        build:
            context: "./"
            args:
                _CI_RUNTIME_GID: "${_CI_RUNTIME_GID}"
                _CI_RUNTIME_HOME: "${_CI_RUNTIME_HOME}"
                _CI_RUNTIME_UID: "${_CI_RUNTIME_UID}"
                _CI_RUNTIME_USER: "${_CI_RUNTIME_USER}"
                PHPFPM_PHP_VERSION: "${PHPFPM_PHP_VERSION}"
        env_file:
            - ".env"
