version: "3.6"
services:
    phpcli:
        build:
            context: "./"
            args:
                _CI_IMAGE_ARTIFACT_DIR: "${_CI_IMAGE_ARTIFACT_DIR}"
                _CI_IMAGE_CI_DIR: "${_CI_IMAGE_CI_DIR}"
                _CI_IMAGE_LOCAL_BIN_DIR: "${_CI_IMAGE_LOCAL_BIN_DIR}"
                _CI_IMAGE_WORK_DIR: "${_CI_IMAGE_WORK_DIR}"
                _CI_IMAGE_APP_DIR: "${_CI_IMAGE_APP_DIR}"
                BASE_PHP_VERSION: "${BASE_PHP_VERSION}"
                COMPOSER_VERSION: "${COMPOSER_VERSION}"
                PHPCLI_PACKAGE_APT: "${PHPCLI_PACKAGE_APT}"
                PHPCLI_PACKAGE_PHP_ENABLE: "${PHPCLI_PACKAGE_PHP_ENABLE}"
                PHPCLI_PACKAGE_PHP_INSTALL: "${PHPCLI_PACKAGE_PHP_INSTALL}"
        env_file:
            - ".env"
