version: "3.6"
services:
    phpclibase:
        build:
            context: "./"
            args:
                _CI_IMAGE_CI_DIR: "${_CI_IMAGE_CI_DIR}"
                BASE_PHP_VERSION: "${BASE_PHP_VERSION}"
                PHPCLI_APT_PACKAGES: "${PHPCLI_APT_PACKAGES}"
        env_file:
            - ".env"
