version: "3.6"
services:
    phpfpmbase:
        image: phpfpmbase_phpfpmbase
        build:
            context: "./"
            args:
                _CI_IMAGE_CI_DIR: "${_CI_IMAGE_CI_DIR}"
                BASE_PHP_VERSION: "${BASE_PHP_VERSION}"
                PHPFPM_APT_PACKAGES: "${PHPFPM_APT_PACKAGES}"
        env_file:
            - ".env"
