version: "3.6"
services:
    phpfpmbase:
        build:
            context: "./"
            args:
                _CI_IMAGE_CI_DIR: "${_CI_IMAGE_CI_DIR}"
                BASE_PHP_VERSION: "${BASE_PHP_VERSION}"
                PHPFPM_PACKAGE_APT: "${PHPFPM_PACKAGE_APT}"
        env_file:
            - ".env"
