version: "3.6"
services:
    phpfpm:
        build:
            context: "./"
            args:
                _CI_IMAGE_CI_DIR: "${_CI_IMAGE_CI_DIR}"
                _CI_IMAGE_LOCAL_BIN_DIR: "${_CI_IMAGE_LOCAL_BIN_DIR}"
                _CI_IMAGE_WORK_DIR: "${_CI_IMAGE_WORK_DIR}"
                _CI_IMAGE_APP_DIR: "${_CI_IMAGE_APP_DIR}"
                PHPFPMBASE_PHP_VERSION: "${PHPFPMBASE_PHP_VERSION}"
                PHPFPM_PACKAGE_PHP_ENABLE: "${PHPFPM_PACKAGE_PHP_ENABLE}"
                PHPFPM_PACKAGE_PHP_INSTALL: "${PHPFPM_PACKAGE_PHP_INSTALL}"
                PHPFPM_PACKAGE_PECL: "${PHPFPM_PACKAGE_PECL}"
        env_file:
            - ".env"
