version: "3.6"
services:
    phpfpm:
        build:
            context: "./"
            args:
                _CI_IMAGE_CI_DIR: "${_CI_IMAGE_CI_DIR}"
                _CI_IMAGE_LOCAL_BIN_DIR: "${_CI_IMAGE_LOCAL_BIN_DIR}"
                _CI_IMAGE_APP_DIR: "${_CI_IMAGE_APP_DIR}"
                PHPFPMBASE_PHP_VERSION: "${PHPFPMBASE_PHP_VERSION}"
                PHPFPM_DOCKER_EXT_PACKAGES: "${PHPFPM_DOCKER_EXT_PACKAGES}"
                PHPFPM_PECL_PACKAGES: "${PHPFPM_PECL_PACKAGES}"
        env_file:
            - ".env"
